#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Oct  4 19:27:01 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class wxAuiNotebook(wx.Notebook):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxAuiNotebook.__init__
        kwds["style"] = 0
        wx.Notebook.__init__(self, *args, **kwds)
        self.InitialTab = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxAuiNotebook.__set_properties
        self.AddPage(self.InitialTab, "Welcome")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxAuiNotebook.__do_layout
        topsizer = wx.BoxSizer(wx.HORIZONTAL)
        self.InitialTab.SetSizer(topsizer)
        # end wxGlade

# end of class wxAuiNotebook


class GladeMainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GladeMainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SplitterWindow = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.ContextPane = wx.Panel(self.SplitterWindow, -1)
        self.TabBook = wxAuiNotebook(self.SplitterWindow, -1)
        
        # Menu Bar
        self.PMWmenubar = wx.MenuBar()
        self.fileMenu = wx.Menu()
        self.fileMenuQuit = wx.MenuItem(self.fileMenu, wx.NewId(), "&Quit", "", wx.ITEM_NORMAL)
        self.fileMenu.AppendItem(self.fileMenuQuit)
        self.PMWmenubar.Append(self.fileMenu, "&File")
        self.SetMenuBar(self.PMWmenubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.onChangeTab, self.TabBook)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GladeMainWindow.__set_properties
        self.SetTitle("Pieberry II")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/home/raif/development/v2Pieberry/pieberry/ui/pieberry.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((862, 546))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GladeMainWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        contextsizer = wx.BoxSizer(wx.HORIZONTAL)
        self.ContextPane.SetSizer(contextsizer)
        self.SplitterWindow.SplitVertically(self.TabBook, self.ContextPane, 551)
        sizer_1.Add(self.SplitterWindow, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def onChangeTab(self, event): # wxGlade: GladeMainWindow.<event_handler>
        print "Event handler `onChangeTab' not implemented!"
        event.Skip()

# end of class GladeMainWindow


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = GladeMainWindow(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
